name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.vscode/**'
      - '.idea/**'

permissions:
  contents: read
  packages: read

jobs:
  mafia-contracts-validate:
    name: Run mafia-contracts release
    secrets: inherit
    uses: ./.github/workflows/mafia-contracts-ci.yaml

  mafia-contracts-release:
    name: Run mafia-contracts release
    secrets: inherit
    uses: ./.github/workflows/mafia-contracts-cd.yaml
    needs: mafia-contracts-validate

  mafia-frontend-validate:
    name: Run mafia-frontend release
    secrets: inherit
    uses: ./.github/workflows/mafia-frontend-ci.yaml

  mafia-frontend-release:
    name: Run mafia-frontend release
    secrets: inherit
    uses: ./.github/workflows/mafia-frontend-cd.yaml
    needs: mafia-frontend-validate
