name: Pull Request validation

on: [pull_request]


jobs:
  mafia-contracts-ci:
    name: Run mafia-contracts validation
    uses: ./.github/workflows/mafia-contracts-ci.yaml

  mafia-frontend-ci:
    name: Run mafia-frontend validation
    uses: ./.github/workflows/mafia-frontend-ci.yaml

